- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /path
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: extract user application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
      args:
        chdir: /app

  - name: Copy cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
 
  - name: deamon reaload and start
    ansible.builtin.systems_service:
      deamon_reload: true
      
 - name: start and enable cart
   ansible.builtin.service:
     name: cart
     state: restarted
     enabled: yes