- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Disable old nodejs and enable nodejs 18
      ansible.builtin.shell: |
        dnf module disable nodejs -y
        dnf module enable nodejs:18 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Extract catalogue application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.shell:
        cmd: npm install
        chdir: /app

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Daemon reload and start
      ansible.builtin.systemd:
        daemon_reload: true
        name: catalogue
        state: restarted
        enabled: yes

    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present

    - name: Get the categories count
      ansible.builtin.shell:
        cmd: mongo --host mongodb.daws76s.cfd --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: Load catalogue data
      ansible.builtin.shell:
        cmd: mongo --host mongodb.daws76s.cfd < /app/schema/catalogue.js
      when: product_count.stdout == '0'

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes

 



  


