- name: Setup MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB package
      ansible.builtin.yum:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

    - name: Allow remote connections to MongoDB
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '127\.0\.0\.1'
        line: '0.0.0.0'
        backrefs: yes

    - name: Restart MongoDB service to apply configuration changes
      ansible.builtin.service:
        name: mongod
        state: restarted
  
  - name: allow remote connections
    ansible.builtin.service:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

    - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: restarted
